---
auth:
  authType: "NONE"
  rememberUsers: true
  restrictAdmin: false
  restrictDetailsDl: false
  restrictIndexerSelection: false
  restrictSearch: false
  restrictStats: false
  users: []
categoriesConfig:
    enableCategorySizes: true
    categories:
        - name: Anime
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 3000
          minSizePreset: 50
          applySizeLimitsToApi: false
          newznabCategories:
          - 5070
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
          subtype: ANIME
        - name: Audio
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 2000
          minSizePreset: 1
          applySizeLimitsToApi: false
          newznabCategories:
          - 3000
          requiredRegex:
          requiredWords: ["mp3", "flac"]
          preselect: true
          searchType: MUSIC
          subtype: NONE
        - name: Audiobook
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 1000
          minSizePreset: 50
          applySizeLimitsToApi: false
          newznabCategories:
          - 3030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MUSIC
          subtype: AUDIOBOOK
        - name: Comic
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 250
          minSizePreset: 1
          applySizeLimitsToApi: false
          newznabCategories:
          - 7030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
          subtype: COMIC
        - name: Console
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 40000
          minSizePreset: 100
          applySizeLimitsToApi: false
          newznabCategories:
          - 1000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
          subtype: NONE
        - name: Ebook
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 100
          minSizePreset:
          applySizeLimitsToApi: false
          newznabCategories:
          - 7020
          - 8010
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: BOOK
          subtype: EBOOK
        - name: FLAC
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 2000
          minSizePreset: 10
          applySizeLimitsToApi: false
          newznabCategories:
          - 3040
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MUSIC
          subtype: NONE
        - name: Movies
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 20000
          minSizePreset: 500
          applySizeLimitsToApi: false
          newznabCategories:
          - 2000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MOVIE
          subtype: NONE
        - name: Movies HD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 20000
          minSizePreset: 3000
          applySizeLimitsToApi: false
          newznabCategories:
          - 2040
          - 2050
          - 2060
          - 2070
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MOVIE
          subtype: NONE
        - name: Movies SD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 3000
          minSizePreset: 500
          applySizeLimitsToApi: false
          newznabCategories:
          - 2030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MOVIE
        - name: MP3
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 500
          minSizePreset: 1
          applySizeLimitsToApi: false
          newznabCategories:
          - 3000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MUSIC
          subtype: NONE
        - name: PC
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 50000
          minSizePreset: 100
          applySizeLimitsToApi: false
          newznabCategories:
          - 4000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
          subtype: NONE
        - name: TV
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 5000
          minSizePreset: 50
          applySizeLimitsToApi: false
          newznabCategories:
          - 5000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: TVSEARCH
          subtype: NONE
        - name: TV HD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 4500
          minSizePreset: 300
          applySizeLimitsToApi: false
          newznabCategories:
          - 5040
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: TVSEARCH
          subtype: NONE
        - name: TV SD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 1000
          minSizePreset: 50
          applySizeLimitsToApi: false
          newznabCategories:
          - 5030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: TVSEARCH
          subtype: NONE
        - name: XXX
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 10000
          minSizePreset: 100
          applySizeLimitsToApi: false
          newznabCategories:
          - 6000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
          subtype: NONE
downloading:
    downloaders: []
    saveTorrentsTo: null
indexers: []
main:
  apiKey: null
  configVersion: 1
  backupEverySunday: true
  dereferer: "http://www.dereferer.org/?$s"
  externalUrl: null
  host: "0.0.0.0"
  logging:
    consolelevel: "INFO"
    historyUserInfoType: "NONE"
    logfilelevel: "INFO"
    logMaxSize: 5
    logIpAddresses: true
    logUsername: false
    markersToLog: []
  port: 5076
  proxyType: NONE
  proxyHost: null
  proxyPort: 1080
  proxyIgnoreLocal: true
  proxyIgnoreDomains: null
  proxyUsername: null
  proxyPassword: null
  repositoryBase: "https://github.com/theotherp"
  showNews: true
  shutdownForRestart: false
  sniDisabledFor: ["nzbgeek.info"]
  ssl: false
  sslKeyStore: null
  sslKeyStorePassword: null
  startupBrowser: true
  theme: "grey"
  updateCheckEnabled: true
  urlBase: null
  useCsrf: true
  useLocalUrlForApiAccess: true
  verifySsl: true
  welcomeShown: false
  xmx: 128
searching:
  alwaysShowDuplicates: false
  applyRestrictions: "NONE"
  duplicateAgeThreshold: 2.0
  duplicateSizeThresholdInPercent: 1.0
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: null
  forbiddenWords: []
  generateQueries: "NONE"
  idFallbackToQueryGeneration: "NONE"
  ignorePassworded: false
  ignoreTemporarilyDisabled: false
  keepSearchResultsForDays: 14
  language: "en"
  loadAllCachedOnInternal: true
  maxAge: null
  nzbAccessType: "REDIRECT"
  removeTrailing: [".mp4", ".mkv", ".subs", ".REPOST", "repost", "~DG~", ".DG", "-DG", "-1", ".1", "(1)", "ReUp", "ReUp2", "-RP", "-AsRequested", "-Obfuscated", "-Scrambled", "-Chamele0n", "-BUYMORE", "-[TRP]", "-DG", ".par2", ".part01", "part01.rar", ".part02.rar", ".jpg", "[rartv]", "[rarbg]", "[eztv]", "English", "Korean", "Spanish", "French", "German", "Italian", "Danish", "Dutch", "Japanese", "Cantonese", "Mandarin", "Russian", "Polish", "Vietnamese", "Swedish", "Norwegian", "Finnish", "Turkish", "Portuguese", "Flemish", "Greek", "Hungarian"]
  requiredRegex: null
  requiredWords: []
  showQuickFilterButtons: true
  timeout: 20
  userAgent: "NZBHydra2"
  userAgents: ["Mozilla", "Sonarr", "Radarr", "CouchPotato", "LazyLibrarian", "NZBGet", "sabNZBd"]
  useOriginalCategories: false
  wrapApiErrors: false