---
auth:
  authHeader: null
  authHeaderIpRanges: []
  authType: "NONE"
  rememberUsers: true
  rememberMeValidityDays: 14
  restrictAdmin: false
  restrictDetailsDl: false
  restrictIndexerSelection: false
  restrictSearch: false
  restrictStats: false
  allowApiStats: true
  users: []
categoriesConfig:
  enableCategorySizes: true
  defaultCategory: "All"
  categories:
    - name: Anime
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 3000
      minSizePreset: 50
      applySizeLimitsToApi: false
      newznabCategories:
        - "5070"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: SEARCH
      subtype: ANIME
    - name: Audio
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 2000
      minSizePreset: 1
      applySizeLimitsToApi: false
      newznabCategories:
        - "3000"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MUSIC
      subtype: NONE
    - name: Audiobook
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 1000
      minSizePreset: 50
      applySizeLimitsToApi: false
      newznabCategories:
        - "3030"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MUSIC
      subtype: AUDIOBOOK
    - name: Comic
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 250
      minSizePreset: 1
      applySizeLimitsToApi: false
      newznabCategories:
        - "7030"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: SEARCH
      subtype: COMIC
    - name: Console
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 40000
      minSizePreset: 100
      applySizeLimitsToApi: false
      newznabCategories:
        - "1000"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: SEARCH
      subtype: NONE
    - name: Ebook
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 100
      minSizePreset:
      applySizeLimitsToApi: false
      newznabCategories:
        - "7020"
        - "8010"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: BOOK
      subtype: EBOOK
    - name: FLAC
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 2000
      minSizePreset: 10
      applySizeLimitsToApi: false
      newznabCategories:
        - "3040"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MUSIC
      subtype: NONE
    - name: Movies
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 20000
      minSizePreset: 500
      applySizeLimitsToApi: false
      newznabCategories:
        - "2000"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MOVIE
      subtype: NONE
    - name: Movies HD
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 20000
      minSizePreset: 3000
      applySizeLimitsToApi: false
      newznabCategories:
        - "2040"
        - "2050"
        - "2060"
        - "2070"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MOVIE
      subtype: NONE
    - name: Movies SD
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 3000
      minSizePreset: 500
      applySizeLimitsToApi: false
      newznabCategories:
        - "2030"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MOVIE
    - name: MP3
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 500
      minSizePreset: 1
      applySizeLimitsToApi: false
      newznabCategories:
        - "3010"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: MUSIC
      subtype: NONE
    - name: PC
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 50000
      minSizePreset: 100
      applySizeLimitsToApi: false
      newznabCategories:
        - "4000"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: SEARCH
      subtype: NONE
    - name: TV
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 5000
      minSizePreset: 50
      applySizeLimitsToApi: false
      newznabCategories:
        - "5000"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: TVSEARCH
      subtype: NONE
    - name: TV HD
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 4500
      minSizePreset: 300
      applySizeLimitsToApi: false
      newznabCategories:
        - "5040"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: TVSEARCH
      subtype: NONE
    - name: TV SD
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 1000
      minSizePreset: 50
      applySizeLimitsToApi: false
      newznabCategories:
        - "5030"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: TVSEARCH
      subtype: NONE
    - name: XXX
      applyRestrictionsType: BOTH
      forbiddenRegex: null
      forbiddenWords: []
      ignoreResultsFrom: NONE
      maxSizePreset: 10000
      minSizePreset: 100
      applySizeLimitsToApi: false
      newznabCategories:
        - "6000"
      requiredRegex: null
      requiredWords: []
      preselect: true
      searchType: SEARCH
      subtype: NONE
downloading:
  downloaders: []
  nzbAccessType: "PROXY"
  saveTorrentsTo: null
  saveNzbsTo: null
  sendMagnetLinks: true
  updateStatuses: true
  showDownloaderStatus: true
  fallbackForFailed: BOTH
genericStorage: {}
indexers: []
main:
  apiKey: null
  backupFolder: "backup"
  backupEveryXDays: 7
  backupBeforeUpdate: true
  configVersion: 17
  databaseCompactTime: 15000
  databaseRetentionTime: 1000
  databaseWriteDelay: 5000
  deleteBackupsAfterWeeks: 4
  disableSslLocally: false
  dereferer: "http://www.dereferer.org/?$s"
  host: "0.0.0.0"
  instanceCounterDownloaded: false
  keepHistory: true
  keepHistoryForWeeks: null
  keepStatsForWeeks: null
  logging:
    consolelevel: "INFO"
    historyUserInfoType: "NONE"
    logfilelevel: "INFO"
    logGc: false
    logMaxHistory: 30
    logIpAddresses: true
    mapIpToHost: true
    logUsername: false
    markersToLog: []
  port: 5076
  proxyType: NONE
  proxyHost: null
  proxyPort: 1080
  proxyIgnoreLocal: true
  proxyIgnoreDomains: []
  proxyUsername: null
  proxyPassword: null
  repositoryBase: "https://github.com/theotherp"
  showNews: true
  showUpdateBannerOnDocker: true
  shutdownForRestart: false
  sniDisabledFor: [ ]
  ssl: false
  sslKeyStore: null
  sslKeyStorePassword: null
  startupBrowser: true
  theme: "grey"
  updateCheckEnabled: true
  updateAutomatically: false
  updateToPrereleases: false
  urlBase: "/"
  useCsrf: true
  verifySsl: true
  verifySslDisabledFor: []
  welcomeShown: false
  xmx: 256
notificationConfig:
  appriseApiUrl: null
  entries: [ ]
  displayNotifications: true
  displayNotificationsMax: 5
searching:
  alwaysConvertIds: "NONE"
  alwaysShowQuickFilterButtons: false
  applyRestrictions: "NONE"
  coverSize: 128
  customQuickFilterButtons: []
  duplicateAgeThreshold: 2.0
  duplicateSizeThresholdInPercent: 1.0
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: null
  forbiddenWords: []
  generateQueries: "INTERNAL"
  generateQueriesFormat: "TITLE"
  globalCacheTimeMinutes: null
  idFallbackToQueryGeneration: "NONE"
  ignorePassworded: false
  ignoreTemporarilyDisabled: false
  ignoreLoadLimitingForInternalSearches: false
  keepSearchResultsForDays: 14
  language: "en"
  languagesToKeep: []
  loadAllCachedOnInternal: true
  loadLimitInternal: 100
  maxAge: null
  minSeeders: null
  removeTrailing: [".mp4", ".mkv", ".subs", ".REPOST", "repost", "~DG~", ".DG", "-DG", "-1", ".1", "(1)", "ReUp", "ReUp2", "-RP", "-AsRequested", "-Obfuscated", "-Scrambled", "-Chamele0n", "-BUYMORE", "-[TRP]", "-DG", ".par2", ".part01", "part01.rar", ".part02.rar", ".jpg", "[rartv]", "[rarbg]", "[eztv]", "English", "Korean", "Spanish", "French", "German", "Italian", "Danish", "Dutch", "Japanese", "Cantonese", "Mandarin", "Russian", "Polish", "Vietnamese", "Swedish", "Norwegian", "Finnish", "Turkish", "Portuguese", "Flemish", "Greek", "Hungarian"]
  requiredRegex: null
  requiredWords: []
  sendTorznabCategories: true
  showQuickFilterButtons: true
  timeout: 20
  transformNewznabCategories: true
  userAgent: "NZBHydra2"
  userAgents: [ "Mozilla", "Sonarr", "Radarr", "CouchPotato", "LazyLibrarian", "Lidarr", "NZBGet", "sabNZBd" ]
  useOriginalCategories: false
  wrapApiErrors: false
